x=[-1:0.05:1];
y=[-2:0.05:2];
[X,Y]=meshgrid(x,y);
fxy=1./(1+(X.^2+Y.^2).^0.5);
figure;
mesh(X,Y,fxy);
xlabel('x axis');
ylabel('y axis');
zlabel('f_{xy}');
[r,c]=find(y==-2);
i=fxy(c,:);
j=X(c,:);
plot(j,i);
hold all;
[r,c]=find(y==-0);
i=fxy(c,:);
j=X(c,:);
plot(j,i);
hold all;
[r,c]=find(y==-1.6);
i=fxy(c,:);
j=X(c,:);
plot(j,i);
axis([-1 1 0.2 1]);
legend('y=-2','y=0','y=1.6');